spring.profiles.active=local
spring.application.name=backend.main

# Configurações globais do Flyway
spring.flyway.locations=\
  classpath:db/migration/identity,\
  classpath:db/migration/company,\
  classpath:db/migration/events
spring.flyway.schemas=identity,company,events
spring.flyway.create-schemas=true
spring.flyway.baseline-on-migrate=false
spring.flyway.out-of-order=false
spring.flyway.validate-on-migrate=true